### ISSUE TITLE
流式调用时异常

### ISSUE THREAD

**Issue by VarleyT** [gulihua10010/chatGptApiSdk#5]
![image](https://user-images.githubusercontent.com/95705895/222944326-906c061e-7189-48b1-934c-fc026165e11a.png)
![image](https://user-images.githubusercontent.com/95705895/222944339-51135a9e-2f9b-4601-a513-dc6b7c2d9f88.png)

**Comment by VarleyT** [comment]
依赖版本是1.0.3

**Comment by soulForLove** [comment]
> 我这边建了一个新的项目 运行是可以的，你的项目是不是之前引入过别的版本的 okhttp 的依赖呢，导致依赖冲突呢

我把之前的版本依赖删了，也是会出现这个在流模式出现
Exception in thread "OkHttp Dispatcher" java.lang.NullPointerException
	at cn.jianwoo.openai.chatgptapi.stream.HttpAsyncClientUtil$1.onFailure(HttpAsyncClientUtil.java:81)
	at okhttp3.internal.sse.RealEventSource.onFailure(RealEventSource.java:105)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:180)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by gulihua10010** [comment]
是一个问题，已经修复并且部署sdk了<version>1.0.4</version> 
同步到中央仓库可以会有延迟
